# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZq3e1sMUHf17Wc_36WnKgss1qvnelCx
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Configures the page structure layout to wide screen viewing
st.set_page_config(page_title="Transfermarkt Performance Dashboard", layout="wide")

# 2. Optimized caching mechanism to prevent re-reading the CSV on every interactive click
@st.cache_data
def load_data():
    return pd.read_csv("processed_players.csv")

df = load_data()

# Header Framework
st.title("⚽ Footballer Performance & Style Analysis Dashboard")
st.markdown("Evaluating player performance vectors, playing styles, and historical market valuation trajectories.")

# ==============================================================================
# INTERACTIVE SIDEBAR FILTER INTERFACES
# ==============================================================================
st.sidebar.header("Filter Panels")

# Position categorization filter
all_positions = df['position'].unique().tolist()
selected_positions = st.sidebar.multiselect("Select Position Group:", all_positions, default=all_positions)

# Playstyle cluster classification filter
all_styles = df['playing_style'].unique().tolist()
selected_styles = st.sidebar.multiselect("Select Profile Playstyle:", all_styles, default=all_styles)

# Range Slider bounded to global valuation extremes
val_min, val_max = int(df['current_value'].min()), int(df['current_value'].max())
selected_value = st.sidebar.slider("Current Market Valuation Range (€)", val_min, val_max, (val_min, val_max))

# Apply combined logic queries across the dataset
filtered_df = df[
    (df['position'].isin(selected_positions)) &
    (df['playing_style'].isin(selected_styles)) &
    (df['current_value'].between(selected_value[0], selected_value[1]))
]

# ==============================================================================
# LIVE STRATEGIC METRICS ROW (KPIs)
# ==============================================================================
col1, col2, col3, col4 = st.columns(4)
col1.metric("Players in Scope", f"{len(filtered_df):,}")
col2.metric("Avg Goals Per 90", f"{filtered_df['goals_per_90'].mean():.2f}")
col3.metric("Avg Market Value", f"€{filtered_df['current_value'].mean():,.0f}")
col4.metric("Avg Valuation Growth", f"€{filtered_df['value_growth_eur'].mean():,.0f}")

st.markdown("---")

# ==============================================================================
# INTERACTIVE DATA VISUALIZATIONS SECTION (PLOTLY)
# ==============================================================================
chart_col1, chart_col2 = st.columns(2)

with chart_col1:
    st.subheader("Playstyle Clusters: Attacking Matrix")
    # Generates a dynamic scatterplot showing scoring output vs creative playmaking
    fig_scatter = px.scatter(
        filtered_df,
        x="assists_per_90",
        y="goals_per_90",
        color="playing_style",
        size="current_value",
        hover_name="name",
        size_max=30,
        labels={"assists_per_90": "Assists per 90 Mins", "goals_per_90": "Goals per 90 Mins"},
        color_discrete_sequence=px.colors.qualitative.Vivid
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

with chart_col2:
    st.subheader("Market Valuation Trajectory vs. Current Value")
    # Creates a custom visualization comparing absolute cost against historical trajectory growth
    fig_trend = px.scatter(
        filtered_df,
        x="current_value",
        y="value_growth_eur",
        color="playing_style",
        hover_name="name",
        labels={"current_value": "Current Valuation (€)", "value_growth_eur": "Market Value Change (Lifetime Delta €)"},
        color_discrete_sequence=px.colors.qualitative.Vivid
    )
    # Visual break reference marking flat growth trajectories
    fig_trend.add_hline(y=0, line_dash="dash", line_color="gray")
    st.plotly_chart(fig_trend, use_container_width=True)

# ==============================================================================
# RAW DATA COMPONENT REGISTRY REGISTER
# ==============================================================================
st.subheader("Filtered Scouting Registry Table")
st.dataframe(
    filtered_df[['name', 'position', 'sub_position', 'playing_style', 'current_value', 'value_growth_eur', 'goals_per_90', 'assists_per_90', 'discipline_per_90']],
    use_container_width=True
)

